try{  
     //e. Thus catch block will be invoked 
     var a =10;
     
     console.log(a);
     console.log(b)
    }catch(e){  
    console.log("There is error which shows "+e); //Handling error  
    }  